language: C

compiler: gcc


before_install:
  - sudo apt-get update
  - sudo apt-get -y install make
  - sudo apt-get -y install cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - cat log/*